# Markov Decision Processes
- Feldman/Valdez-Flores: Chapter 12, EXCLUDING: 12.3.1, 12.3.3, 12.4.2, 12.5


## **12.1 Basic Definitions**

***Example 12.1***: Let $X = \{X_0, X_1, ...\}$ be a a stochastic process with state space $E = \{a, b, c, d \}$. Process will represent a machine that can be in one of four operating conditions denoted by the states a through d indicating increasing levels of deterioration. As the machine deteriorates, not only is it more expensive to operate, but also production is lost. Standard maintenance activities are always carried out in states b through d so that the machine may improve due to maintenance; however, improvement is not guaranteed. Process has action space $A = \{1, 2 \}$ which gives the decisions possible at each step - at each step there are two possible actions: use an inexperienced operator (Action 1) or use an experienced operator (Action 2).

Two cost vectors and two Markov matrices:

$f_1 = (100,125,150,500)$

$f_2 = (300,325,350,600)$

$P_1 = \begin{bmatrix}
0.1 & 0.3 & 0.6 & 0.0 \\
0.0 & 0.2 & 0.5 & 0.3 \\
0.0 & 0.1 & 0.2 & 0.7 \\
0.8 & 0.1 & 0.0 & 0.1 \\
\end{bmatrix}$

$P_2 = \begin{bmatrix}
0.6 & 0.3 & 0.1 & 0.0 \\
0.75 & 0.1 & 0.1 & 0.05 \\
0.8 & 0.2 & 0.0 & 0.0 \\
0.9 & 0.1 & 0.0 & 0.0 \\
\end{bmatrix}$


- if, at time $n$, the process is in state $i$ and the decision $k$ is made, then a cost of $f_k(i)$ is incurred and the probability that the next state will be $j$ is given by $P_k(i, j)$
- if $X_n = a$ and decision 1 is made, then a cost of 100 is incurred (representing the operator cost, lost production cost, and machine operation cost) and $Pr\{X_n+1 = a\} = 0.1$
- if $X_n = d$ and decision 2 is made, then a cost of 600 is incurred (representing the operator cost, machine operation cost, major maintenance cost, and lost-production cost) and $Pr\{X_n+1 = a\} = 0.9$


$$
X_n = i \implies D_n = k \implies f_k(i) \implies P_k(i, j)
$$
$$
\text{Observe state} \implies \text{Take action} \implies \text{Incur cost} \implies \text{Transition to next state}
$$

- $X = \{X_0, X_1, ...\}$ is the system description process
- $D = \{D_0, D_1, ...\}$ is the decision process

***Definition 12.1:*** Let $X$ be a system description process with state space $E$ and let $D$ be a decision process with action space A. The process $(X,D)$ is a Markov Decision Process if, for $j \in E$, and $n = 0,1, ··· ,$ the following holds

$$
\Pr\{X_{n+1} = j \mid X_0, D_0, \dots, X_n, D_n\} = \Pr\{X_{n+1} = j \mid X_n, D_n\}
$$

Futhermore, for each $k \in A$, let $\textbf{f}_k$ be the cost vector and $\textbf{P}_k$ be a Markov matrix. Then, 

$$
\Pr\{X_{n+1} = j \mid X_n = i, D_n = k\} = P_k(i, j)
$$

and the cost $f_k(i)$ is incurred whenever $X_n = i$ and $D_n = k$\

- Guiding Question: "How can decisions be made as to minimize costs?" - "What do we mean by minimize?"

***Definition 12.2:*** A policy is any rule, using current information, past information, and/or randomization that specifies which action to take at each point in time. The set of all (decision) policies is denoted by $\mathcal{D}$

Examples of policies from Example 12.1:
- **Policy 1:** Always choose action 1, independent of the state for $X$, i.e., let $D_n \equiv 1$ for all $n$.
- **Policy 2:** If $X_n$ is in state $a$ or $b$, let $D_n = 1$; if $X_n$ is in state $c$ or $d$, let $D_n = 2$.
- **Policy 3:** If $X_n$ is in state $a$ or $b$, let $D_n = 1$; if $X_n$ is in state $c$, toss a (fair) coin and let $D_n = 1$ if the toss results in a head and let $D_n = 2$ if it results in a tail; if $X_n$ is in state $d$, let $D_n = 2$.
- **Policy 4:** Let $D_n \equiv 1$ for $n = 0$ and $1$. For $n \geq 2$, if $X_n > X_{n-1}$ and $X_{n-2} = a$, let $D_n = 1$; if $X_n > X_{n-1}$, $X_{n-2} = b$, and $D_{n-1} = 2$ let $D_n = 1$; otherwise, let $D_n = 2$.

<br>

- The Markov decision process is not necessarily a Markov chain, because we can allow decisions to depend upon history

<br>

Minimization criteria used: 
- (1) expected total discounted cost
- (2) average long-run cost


### ***12.1.1 Expected Total Discounted Cost Criterion***

- Equivalent to using a present worth calculation for the basis of decision making
  - Bond pricing, DCF, etc
- The expected total discounted cost for a particular Markov decision process: $E[\sum_{n=0}^{\infty} \alpha^n \mathcal{f}_{D_n}(X_n)]$
  - at time $n = 1$ has a present value of $\alpha$ at time $n = 0$
  - $\alpha = 1/(1+r))$

Example: From example 12.1, Policy 1 is chosen (i.e., the inexperienced operator is always used), and a discount factor of $\alpha = 0.95$ (equivalent to a rate of return of approximately 5.3% per period) is used. Then this reduces to the computation of the total discounted cost of a standard Markov chain. Expected total discounted cost is gived by $(\textbf{I} - \alpha \textbf{P}_1)^{-1} \textbf{f}_1$ $\implies$ $\textbf{v} = (4502,4591,4676,4815)^T$ $\implies$ if the process starts in state $a$, the expected present value of all future costs is 4502.


There exists a dependence on the specific policy before expectations can be taken. Subscript with the expectation operator denotes an expectation under the probability law specified by the policy $d \in \mathcal{D}$. The total discounted value of a Markov decision process under a discount factor of $\alpha$ using the policy $d \in \mathcal{D}$ will be denoted by $v_d^{\alpha}$:

$$
v_d^{\alpha}(i) = E_d \Bigg[\sum_{n=0}^{\infty} \alpha^n \mathcal{f}_{D_n}(X_n) \mid X_0 = i \Bigg]
$$

for $i \in E$ and $0 < \alpha < 1$

The discounted cost optimization problem can be stated as: Find $d^{\alpha} \in \mathcal{D}$ such that $v_{d^\alpha}^{\alpha(i)} = v^{\alpha}(i)$ where the vector $\textbf{v}^{\alpha}$ is defined for $i \in E$ by

$$
v^{\alpha}(i) = \min_{d \in \mathcal{D}} v_d^{\alpha}(i)
$$

- the existence of an optimal policy can be a difficult question when the state space is infinite
- we shall only consider problems in which its existence is assured by assuming that both the state space and action space are finite

### ***12.1.2 Average Long-Run Cost Criterion***

- Using an infinite horizon planning period, the total (undiscounted) cost may be infinite for all possible decisions so that total cost cannot be used to distinguish between alternative policies.
- We can use cost per transition for comparison allowing alternatives to be evaluated for an infinite horizon planning period
- A commonly used criterion: $\lim_{m \to \infty} \frac{1}{m} \sum_{n=0}^{m-1} f_{D_n}(X_n)$
- For example, assume that Policy 1 is used; thus, Action 1 is always chosen.
  - long-run cost can be calculated by the steady-state probabilities using the matrix $\textbf{P}_1$ which gives us $\textbf{π} = (0.253,0.167,0.295,0.285)$
  - $\textbf{π}$ $\cdot$ $\textbf{f}_1$ $= 232.925$

For a fixed policy $d \in \mathcal{D}$ the average long-run cost for the Markov decision process will be denoted by $\phi_d$:

$$
\phi_d = \lim_{m \to \infty} \frac{f_{D_0}(X_0) + \cdots + f_{D_{m-1}}(X_{m-1})}{m}
$$

The optimization problem can be stated as: Find $d^* \in \mathcal{D}$ such that $\phi_{d^*} = \phi^*$, where $\phi^*$ is defined by:
$$
\phi^* = \min_{d \in \mathcal{D}} \phi_d
$$ 


## **12.2 Stationary Policies**

**Definition 12.3:** An action function is a vector which maps the state space into the action space, i.e., an action function assigns an action to each state.
- if **a** is an action function, then $a(i) \in A$ for each $i \in E$. Policy 2 is equivalent to the action function $\textbf{a} = (1,1,2,2)$, where the action space is $A = \{ 1,2 \}$.

**Definition 12.4:** A stationary policy is a policy that can be defined by an action function. The stationary policy defined by the function a takes action $a(i)$ at time $n$ if $X_n = i$, independent of previous states, previous actions, and time $n$.
- stationary policy is independent of time
- stationary policy is a non-randomized policy that only depends on the current state of the process and thus ignores history
- it is a Markov decision process under a stationary policy is always a Markov chain

**Property 12.1**. If the state space E is finite, there exists a stationary policy that solves the problem given in Eq. (12.1). Furthermore, if every stationary policy yields an irreducible Markov chain, there exists a stationary policy that solves the problem given in Eq. (12.2). (The optimum policy may depend on the discount factor and may be different for Eqs. (12.1) and (12.2).)
- Eq 12.1 is Expected Total Discounted Cost Criterion optimization problem
- Eq 12.2 is Average Long-Run Cost Criterion optimization problem

## **12.3 Discounted Cost Algorithms**
- Based on a fixed-point property that holds for the optimal value function
- a function is called invariant with respect to an operation if the operation does not vary the function
  - steady-state vector **π** is the invariant vector for the Markov matrix **P** b/c **πP** does not vary the vector **π**
  - the invariant property as applied to Markov decision processes will be recognized as the standard dynamic programming recursive relationship
  - involves minimizing current costs plus all future costs, where the future costs must be discounted to the present in order to produce a total present value

**Property 12.2. Fixed-Point Theorem for Markov Decision Processes:** \
$\textbf{v}^a$ is the  optimal value function of the Expected Total Discounted Cost Criterion optimization problem with $0 < \alpha < 1$. The function $\textbf{v}^a$ satisfies, for each $i \in E$ the following:
$$
\textbf{v}^a(i) = \min_{k \in A}\{f_k(i) + \alpha \sum_{j \in E} P_k(i, j)v^{\alpha}(j) \}
$$

- it is the only function satisfying this property
- provides a means to determine if a given function happens to be the optimal function

**Property 12.3:** $\textbf{v}^a$ is the  optimal value function of the Expected Total Discounted Cost Criterion optimization problem with $0 < \alpha < 1$. Define an action function for each $i \in E$ the following:
$$
a(i) = \underset{k \in A}{\mathrm{argmin}} \{f_k(i) + \alpha \sum_{j \in E} P_k(i, j)v^{\alpha}(j) \}
$$

- The stationary policy defined by the action function **a** is an optimal policy.
- Property 12.3 tells how to obtain the optimal policy once $v^\alpha$ is known (we dont know how to get $v^\alpha$ yet)

**Example:** The optimal value function for the machine problem given in Example 12.1 is $\textbf{v}^\alpha = (4287,4382,4441,4613)$ for $\alpha = 0.95$
- verify the assertion through the Fixed-Point Theorem for Markov Decision Processes
  - $v^{\alpha}(a)$ = $\min{\{f_1[0] + 0.95 * P_1[0] \times \textbf{v}^\alpha, f_2[0] + 0.95 * P_2[0] \times \textbf{v}^\alpha \}} $
  - $v^{\alpha}(b)$ = $\min{\{f_1[1] + 0.95 * P_1[1] \times \textbf{v}^\alpha, f_2[1] + 0.95 * P_2[1] \times \textbf{v}^\alpha \}} $
  - $v^{\alpha}(c)$ = $\min{\{f_1[2] + 0.95 * P_1[2] \times \textbf{v}^\alpha, f_2[2] + 0.95 * P_2[2] \times \textbf{v}^\alpha \}} $
  - $v^{\alpha}(d)$ = $\min{\{f_1[3] + 0.95 * P_1[3] \times \textbf{v}^\alpha, f_2[3] + 0.95 * P_2[3] \times \textbf{v}^\alpha \}} $

In [53]:
import numpy as np

In [54]:
f1 = np.array([100, 125, 150, 500])
f2 = np.array([300, 325, 350, 600])

p1 = np.matrix(
    [
        [0.1, 0.3, 0.6, 0.0],
        [0.0, 0.2, 0.5, 0.3],
        [0.0, 0.1, 0.2, 0.7],
        [0.8, 0.1, 0.0, 0.1],
    ]
)
p2 = np.matrix(
    [
        [0.6, 0.3, 0.1, 0.0],
        [0.75, 0.1, 0.1, 0.05],
        [0.8, 0.2, 0.0, 0.0],
        [0.9, 0.1, 0.0, 0.0],
    ]
)

v_super_alpha = np.array([4287, 4382, 4441, 4613])

alpha = 0.95

In [55]:
optimal_values = []
for i in range(0, 4):
    action_1 = (float(f1[i] + alpha * np.dot(p1[i], v_super_alpha)[0]), "action1", i+1)
    action_2 = (float(f2[i] + alpha * np.dot(p2[i], v_super_alpha)[0]), "action2", i+1)
    optimal_values.append(action_1 if action_1[0] < action_2[0] else action_2)

optimal_values

C:\Users\chris\AppData\Local\Temp\ipykernel_6036\3814733425.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  action_1 = (float(f1[i] + alpha * np.dot(p1[i], v_super_alpha)[0]), "action1", i+1)
C:\Users\chris\AppData\Local\Temp\ipykernel_6036\3814733425.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  action_2 = (float(f2[i] + alpha * np.dot(p2[i], v_super_alpha)[0]), "action2", i+1)


[(4287.504999999999, 'action1', 1),
 (4381.76, 'action1', 2),
 (4440.7, 'action2', 3),
 (4612.645, 'action1', 4)]

- Since, for each $i \in E$, the minimum of the two values yielded the asserted value of $v^\alpha(i)$, we know that it is optimum by Property 12.2
- Can also pick out the argument (i.e., action) that resulted in the minimum value
  - State $i = a$, the first action yielded the minimum
  - State $i = b$, the first action yielded the minimum
  - State $i = c$, the second action yielded the minimum
  - State $i = d$, the first action yielded the minimum
- Therefore, from Property 12.3, the stationary optimal policy is defined by the action function $\textbf{a} = (1,1,2,1).$

### **12.3.2 Policy Improvement for Discounted Costs**
- An algorithm that focuses on the policy and then calculates the value associated with that particular policy
- Result is that convergence is significantly faster, but there are more calculations for each iteration say compared to a Value Improvement for Discounted Costs algo

**Property 12.5. Policy Improvement Algorithm:** The following iteration procedure will yield the optimal value function as defined by Eq 12.1 (Expected Total Discounted Cost Criterion optimization problem) and its associated optimal stationary policy:

**Step 1.** Make sure that $\alpha < 1$, set $n = 0$, and define the action function $a_0$ by:
$$
a_0(i) = \arg\min_{k \in A} f_k(i)
$$
for each $i \in E$.

**Step 2.** Define the matrix $P$ and the vector $f$ by:
$$
f(i) = f_{a_n(i)}(i)
$$
$$
P(i, j) = P_{a_n(i)}(i, j)
$$
for each $i, j \in E$.

**Step 3.** Define the value function $v$ by:
$$
v = (I - \alpha P)^{-1}f
$$

**Step 4.** Define the action function $a_{n+1}$ by:
$$
a_{n+1}(i) = \arg\min_{k \in A} \left\{ f_k(i) + \alpha \sum_{j \in E} P_k(i, j) v(j) \right\}
$$
for each $i \in E$.

**Step 5.** If $a_{n+1} = a_n$, let $v_\alpha = v$, $a_\alpha = a_n$, and stop; otherwise, increment $n$ by one and return to Step 2.


In [56]:
def policy_improvement_for_discounted_costs_algoritm(fs, Ps, alpha, num_iterations=100):
    num_states = len(fs[0])
    # Initial policy
    current_policy = np.zeros(num_states, dtype=int)
    for _ in range(num_iterations):
        f = np.array([fs[current_policy[i]][i] for i in range(num_states)])
        P = np.vstack([Ps[current_policy[i]][i, :] for i in range(num_states)])
        v = np.linalg.inv(np.eye(num_states) - alpha * P) @ f

        # Policy improvement
        new_policy = np.zeros_like(current_policy)
        for i in range(num_states):
            # Evaluate each action's value at state i
            # Correcting the dimension of v
            q_values = [fs[a][i] + alpha * (Ps[a][i, :] @ v.T) for a in range(len(fs))]
            # Update policy
            new_policy[i] = np.argmin(q_values)

        # Check for convergence (if policy does not change)
        if np.array_equal(new_policy, current_policy):
            return v, current_policy
        current_policy = new_policy

    return v, current_policy

In [57]:
fs = [f1, f2]
Ps = [p1, p2]

optimal_value, optimal_policy = policy_improvement_for_discounted_costs_algoritm(fs, Ps, alpha)
optimal_value, optimal_policy

(matrix([[4287.40288177, 4381.63406971, 4440.93666339, 4612.90765388]]),
 array([0, 0, 1, 0]))

## **12.4 Average Cost Algorithms**
- Average cost criterion problem is slightly more difficult than the discounted cost criterion problem because it was the discount factor that produced a fixed-point
- A recursive equation that is analogous to Property 12.2 as follows:

**Property 12.8.** Assume that every stationary policy yields a Markov chain with only one irreducible set. There exists a scalar $\phi^*$ and a vector $h$ such that, for all $i \in E$,

$$
\phi^* + h(i) = \min_{k \in A} \left\{ f_k(i) + \sum_{j \in E} P_k(i, j) h(j) \right\}.
$$

The scalar $\phi^*$ is the optimal cost as defined by Eq. 12.2 (Average Long-Run Cost Criterion optimization problem), and the optimal action function is defined by

$$
a(i) = \arg\min_{k \in A} \left\{ f_k(i) + \sum_{j \in E} P_k(i, j) h(j) \right\}.
$$

The vector $\textbf{h}$ is unique up to an additive constant.


- use this property to determine if the optimal policy previously determined for a discount factor of 0.95 is also the optimal policy under the average cost criterion
- would like to determine if the stationary policy defined by $\textbf{a} = (1,1,2,1)$ is optimal using the long-run average cost criterion
- solve:

$$
\begin{align*}
\phi^* + h_a &= 100 + 0.1 h_a + 0.3 h_b + 0.6 h_c, \\
\phi^* + h_b &= 125 + 0.2 h_b + 0.5 h_c + 0.3 h_d, \\
\phi^* + h_c &= 350 + 0.8 h_a + 0.2 h_b, \\
\phi^* + h_d &= 500 + 0.8 h_a + 0.1 h_b + 0.1 h_d.
\end{align*}
$$

In [58]:
A = np.array(
    [
        [1, -0.3, -0.6, 0],  # From eq1
        [1, 0.8, -0.5, -0.3],  # From eq2
        [1, -0.2, 1, 0],  # From eq3
        [1, -0.1, 0, 0.9],  # From eq4
    ]
)

B = np.array([100, 125, 350, 500])

solution = np.linalg.solve(A, B)
phi_star = solution[0]
h = np.append([0], solution[1:]).tolist()

print("phi*:", phi_star)
print("vector h:", h)

phi*: 219.23774954627947
vector h: [0.0, 97.09618874773139, 150.18148820326678, 322.746521476104]


- these values have been determined so that for each $k = a(i)$ so $\phi^* + h(i) = f_k(i) + \textbf{P}_\textbf{k} \textbf{h}(i)$
- to determine optimality, we must verify that for each $k \neq a(i)$ so $\phi^* + h(i) \leq f_k(i) + \textbf{P}_\textbf{k} \textbf{h}(i)$

$$
\begin{align*}
\phi^* + h_a &\leq 300 + 0.6 h_a + 0.3 h_b + 0.1 h_c, \\
\phi^* + h_b &\leq 325 + 0.75 h_a + 0.1 h_b + 0.1 h_c + 0.05 h_d, \\
\phi^* + h_c &\leq 150 + 0.1 h_b + 0.2 h_c + 0.7 h_d, \\
\phi^* + h_d &\leq 600 + 0.9 h_a + 0.1 h_b.
\end{align*}
$$

In [59]:
coefficients = np.array([
    [0.6, 0.3, 0.1, 0.0],  # Coefficients for h_a, h_b, h_c, h_d in the first inequality
    [0.75, 0.1, 0.1, 0.05], # Coefficients for h_a, h_b, h_c, h_d in the second inequality
    [0.0, 0.1, 0.2, 0.7],   # Coefficients for h_a, h_b, h_c, h_d in the third inequality
    [0.9, 0.1, 0.0, 0.0]    # Coefficients for h_a, h_b, h_c, h_d in the fourth inequality
])
constants = [300, 325, 150, 600]

lhs = phi_star + h
rhs = [constants[i] + np.dot(h, co) for i, co in enumerate(coefficients)]
print(lhs)
print(rhs)
inequalities_hold = np.all(lhs <= rhs)
inequalities_hold

[219.23774955 316.33393829 369.41923775 541.98427102]
[344.1470054446461, 365.865093768905, 415.6684815486993, 609.7096188747731]


True

- once the optimal policy is known, the value $\phi^*$ can be obtained by the long-run probabilities dot cost

In [60]:
P_super_a = np.array([
    [0.1, 0.3, 0.6, 0.0],
    [0.0, 0.2, 0.5, 0.3],
    [0.8, 0.2, 0.0, 0.0],
    [0.8, 0.1, 0.0, 0.1]
])
row_sums = P_super_a.sum(axis=1)
print("Row sums:", row_sums)

# Solve for the stationary distribution of the Markov chain
# Create the matrix (I - P^T + 1v^T) where 1 is a column vector of all ones and v is a row vector of all ones
size = P_super_a.shape[0]
A = np.eye(size) - P_super_a.T + np.ones((size, size))
b = np.ones(size)

# Solve the linear system to find the stationary distribution
stationary_distribution = np.linalg.solve(A, b)
print(stationary_distribution)

cost_vector_g = np.array([100, 125, 350, 500])

np.dot(stationary_distribution, cost_vector_g)

Row sums: [1. 1. 1. 1.]
[0.36297641 0.22867514 0.33212341 0.07622505]


219.2377495462795

![img](images/feldman_flores_table12.1.jpg)

The value for each component in the vector $(1 - \alpha)v_\alpha$ approaches $\phi^*$ as the discount factor approaches one. To understand this, remember that the geometric series is given by:

$$
\sum_{n=0}^\infty \alpha^n = \frac{1}{1 - \alpha};
$$

thus, if a cost of $c$ is incurred every period with a discount factor of $\alpha$, its total value would be:

$$
v = \frac{c}{1 - \alpha}.
$$

Or conversely, a total cost of $v$ is equivalent to an average per period cost of:

$$
c = (1 - \alpha)v.
$$

**Property 12.9:**. Let $\textbf{v}^\alpha$ be the optimal value function defined by Eq 12.1 (Expected Total Discounted Cost Criterion optimization problem), let $\phi^*$ be the optimal cost defined by Eq 12.2 (Average Long-Run Cost Criterion optimization problem), and assume that every stationary policy yields a Markov chain with only one irreducible set. Then

$$
\lim_{\alpha \to 1} (1 - \alpha)v^\alpha(i) = \phi^*
$$

for any $i \in E$.

**Property 12.10:** Let $\textbf{v}^\alpha$ be the optimal value function defined by Eq 12.1 (Expected Total Discounted Cost Criterion optimization problem), let $\phi^*$ be the optimal cost defined by Eq 12.2 (Average Long-Run Cost Criterion optimization problem) and let $\textbf{h}$ be the vector defined by Property 12.8. Then

$$
\lim_{\alpha \to 1} v^\alpha(i) - v^\alpha(j) = h^\alpha(i) - h^\alpha(j)
$$

for any $i, j \in E$.

- This property is the justification for arbitrarily setting $h(a) = 0$ when we solve for $\phi^∗$ and h. In fact, it is legitimate to pick any single state and set its $\textbf{h}$ value equal to any given number

### **12.4.1 Policy Improvement for Average Costs**

- Begins with an arbitrary policy, determines the $\phi^*$ and $h$ values associated with it, and then either establishes that the policy is optimal or produces a better policy

**Property 12.11. Policy Improvement Algorithm:** The following iteration procedure will yield the optimal value function as defined by Eq 12.2 (Average Long-Run Cost Criterion optimization problem) and its associated optimal stationary policy:

**Step 1.** Set $n = 0$, let the first state in the state space be denoted by the number 1, and define the action function $\textbf{a}_0$ by:
$$
a_0(i) = \arg\min_{k \in A} f_k(i)
$$
for each $i \in E$.

**Step 2.** Define the matrix $\textbf{P}$ and the vector $\textbf{f}$ by:
$$
f(i) = f_{a_n(i)}(i)
$$
$$
P(i, j) = P_{a_n(i)}(i, j)
$$
for each $i, j \in E$.

**Step 3.** Determine values for $\phi$ and $\textbf{h}$ by solving the system of equations given by:
$$
\phi + \textbf{h} = \textbf{f} + \textbf{Ph},
$$
where $h(1) = 0$.

**Step 4.** Define the action function $\textbf{a}_{n+1}$ by:
$$
a_{n+1}(i) = \arg\min_{k \in A} \{ f_k(i) + \sum_{j \in E} P_k(i, j) h(j) \}
$$
for each $i \in E$.

**Step 5.** If $\textbf{a}_{n+1} = \textbf{a}_n$, let $\phi^* = \phi$, $\textbf{a}^* = \textbf{a}_n$, and stop; otherwise, increment $n$ by one and return to Step 2.



In [126]:
def policy_improvement_for_average_costs_algoritm(fs, Ps):
    n = 0
    a_prev = [1,1,1,1]
    while True:
        P = Ps[n]
        f = fs[n]
        A = []
        current_policy = np.zeros(len(f), dtype=int)
        for i in range(0, len(f)):
            curr_row = P[i]
            new_row = [0] * len(f)
            new_row[0] = 1
            for j, val in enumerate(curr_row):
                if j == 0:
                    continue
                if j == i:
                    new_row[j] = (1 - val)
                else:
                    new_row[j] = -val
                    
            A.append(new_row)
            
        solution = np.linalg.solve(A, f)
        phi_star = solution[0]
        h = np.append([0], solution[1:])
        
        a_new_policy = np.zeros_like(current_policy) 
        for i in range(0, len(f)):
            q_values = [fs[a][i] + (Ps[a][i, :] @ h.T) for a in range(len(fs))]
            a_new_policy[i] = np.argmin(q_values) + 1

        if np.array_equal(a_new_policy, a_prev):
            return a_new_policy, phi_star, h
        
        a_prev = a_new_policy
        n = n + 1
                

In [127]:
p1 = np.array(
    [
        [0.1, 0.3, 0.6, 0.0],
        [0.0, 0.2, 0.5, 0.3],
        [0.0, 0.1, 0.2, 0.7],
        [0.8, 0.1, 0.0, 0.1],
    ]
)
p2 = np.array(
    [
        [0.1, 0.3, 0.6, 0.0],
        [0.0, 0.2, 0.5, 0.3],
        [0.8, 0.2, 0.0, 0.0],
        [0.8, 0.1, 0.0, 0.1],
    ]
)
Ps = [p1, p2]

fs = [[100, 125, 150, 500], [100, 125, 350, 500]]

policy_improvement_for_average_costs_algoritm(fs, Ps)

(array([1, 1, 2, 1]),
 219.23774954627947,
 array([  0.        ,  97.09618875, 150.1814882 , 322.74652148]))